import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
import groupMaster from '../groupMaster/model';
;

const sectorMaster = sequelize.define('sector_master', {
    sector_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    sector_name: {
        type: Sequelize.STRING,
        allowNull: false // The name of the city
    },
    group_id: {//Foreign key linked to the group master table.
        type: Sequelize.UUID,
        allowNull: false,
        references: {
            // This is a reference to another model
            model: groupMaster,
            // This is the column name of the referenced model
            key: 'group_id',
        }
    },
    file_path:{
        type: Sequelize.STRING,
        allowNull: true // The path to the file
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'sector_master',
    timestamps: true
});

module.exports = sectorMaster;