import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
;

const calculationMethodologyMaster = sequelize.define('calculation_methodology_master', {
    calculation_methodology_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    calculation_methodology_name: {
        type: Sequelize.STRING,
        allowNull: false // The name of the calculation methodology
    },
    gwp_value: {
        type: Sequelize.STRING,
        allowNull: false
    },
    gwp_value_for_co2: {
        type: Sequelize.STRING,
        allowNull: false 
    },
    gwp_value_for_ch4: {
        type: Sequelize.STRING,
        allowNull: false 
    },
    gwp_value_for_n2o: {
        type: Sequelize.STRING,
        allowNull: false
    },
    year: {
        type: Sequelize.STRING,
        allowNull: false
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'calculation_methodology_master',
    timestamps: true
});

module.exports = calculationMethodologyMaster;