import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
import uomMaster from '../uomMaster/model';
;

const categoryMaster = sequelize.define('conversion_master', {
    conversion_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    uom_id: {//Foreign key linked to the uom master table.
        type: Sequelize.UUID,
        allowNull: false,
        references: {
            // This is a reference to another model
            model: uomMaster,
            // This is the column name of the referenced model
            key: 'uom_id',
        }
    },
    type: {
        type: Sequelize.ENUM,
        values: ['Scope 1', 'Scope 2', 'Scope 3'],
        allowNull: true // The type of conversion
    },
    uom2_id: {//Foreign key linked to the uom master table.
        type: Sequelize.UUID,
        allowNull: false,
        references: {
            // This is a reference to another model
            model: uomMaster,
            // This is the column name of the referenced model
            key: 'uom_id',
        }
    },
    operator:{
        type: Sequelize.STRING,
        allowNull: true // The path to the file
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'conversion_master',
    timestamps: true
});

module.exports = categoryMaster;