import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
;

const sourceMaster = sequelize.define('source_master', {
    source_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    source_name: {
        type: Sequelize.STRING,
        allowNull: false // The name of the source
    },
    source_description: {
        type: Sequelize.STRING,
        allowNull: true // A detailed description of the source
    },
    source_link1: {
        type: Sequelize.STRING,
        allowNull: true // The link to the source
    },
    file_path:{
        type: Sequelize.STRING,
        allowNull: true // The path to the file
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'source_master',
    timestamps: true
});

module.exports = sourceMaster;