import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
import licenseTypeMaster from '../licenseTypeMaster/model';
;

const licenseMaster = sequelize.define('license_master', {
    license_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    url: {
        type: Sequelize.STRING,
        allowNull: false // The name of the city
    },
    license_type_id: {//Foreign key linked to the license type table.
        type: Sequelize.UUID,
        allowNull: false,
        references: {
            // This is a reference to another model
            model: licenseTypeMaster,
            // This is the column name of the referenced model
            key: 'license_type_id',
        }
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'license_master',
    timestamps: true
});

module.exports = licenseMaster;