import sequelize from '../../../config/database'; // Import the Sequelize instance
import Sequelize from 'sequelize';
;

const ghgProtocolCategoryMaster = sequelize.define('ghg_protocol_category_master', {
    ghg_protocol_category_id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue:Sequelize.UUIDV4, // UUID generated by Sequelize
    },
    ghg_protocol_category_name: {
        type: Sequelize.STRING,
        allowNull: false // The name of the ghg protocol category
    },
    scope: {
        type: Sequelize.ENUM,
        values: ['Scope 1', 'Scope 2', 'Scope 3'],
        allowNull: true // The scope of the ghg protocol category
    },
    created_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who created the record
    },
    updated_by: {
        type: Sequelize.STRING,
        allowNull: true // Identifier for the user who last updated the record
    },
    is_deleted: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: process.env.IS_DELETED_NO // Flag 1 indicate if the record is deleted
    },
}, {
    tableName: 'ghg_protocol_category_master',
    timestamps: true
});

module.exports = ghgProtocolCategoryMaster;